server:
  port: 8089


#spring.cloud.config.server.git.uri=ssh://localhost/config-repo
#spring.cloud.config.server.git.clone-on-start=true
#security.user.name=root
##security.user.password=s3cr3t

spring:
  application:
    name: config-service
  cloud:
    config.server.git.uri: https://github.com/tourem/config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}